server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: postgres
    password: postgres
      #PostgreSQL驱动
    driver-class-name: org.postgresql.Driver